name: Verify PR

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify artifact
        run: |
          ./gradlew wrapper
          ./gradlew runData
          ./gradlew build